import type { Metadata } from "next";
import { Montserrat } from "next/font/google"; 
import "./globals.css";

// Load Montserrat font
const montserrat = Montserrat({
  subsets: ["latin"], 
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <head>
        <link rel="shortcut icon" href="/Landing Images/Icon.svg" type="image/x-icon" />
      </head> */}
      <body
        className={`${montserrat.className} antialiased`} 
      >
        {children}
      </body>
    </html>
  );
}
